# Generated by Django 3.1.5 on 2021-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210407_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(default=None, to='mainapp.Product', verbose_name='Избранное'),
        ),
    ]
