# Generated by Django 3.1.5 on 2021-05-14 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210422_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
