# Generated by Django 3.1.5 on 2021-04-13 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210407_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус корзины',
                'verbose_name_plural': 'Статусы корзин',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cartstatus', verbose_name='Статус'),
        ),
    ]
