# Generated by Django 3.1.5 on 2021-04-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210413_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cartstatus', verbose_name='Статус'),
        ),
    ]
