# Generated by Django 3.1.5 on 2021-04-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210413_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Адресс')),
                ('final_price', models.IntegerField(verbose_name='Общая цена')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('comment', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainapp.orderstatus')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
