# Generated by Django 3.1.5 on 2021-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210413_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Адресс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
