# Generated by Django 3.1.5 on 2021-04-15 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210413_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stateproduct',
            options={'verbose_name': 'Состояние товара', 'verbose_name_plural': 'Состояния товаров'},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель'),
            preserve_default=False,
        ),
    ]
