# Generated by Django 3.1.5 on 2021-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210415_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='Купил'),
        ),
    ]
